### ISSUE TITLE
Forwarding with Nginx/User Info/Socket.io

### ISSUE THREAD

**Issue by Casuallynoted** [maccam912/docker-apache-wave#2]
Hey there!

I know this is super outdated code and kinda silly to host nowadays but I've been doing it for fun! Been having some trouble with Nginx and I think it might be related to my nginx server config or possibly socket.io.  

This is my current server config:
https://pastebin.com/STpDd410

I'm noticing then when I try to load pages via the Nginx proxied URL (https://wave.casually.cat), the content of waves doesn't show:

![image](https://user-images.githubusercontent.com/6272557/102117824-cd4f7b80-3e0c-11eb-83b3-b6ed2d02f282.png)

However, when I go locally they do... except services are shown as being "offline: and I get an error about things not working like they should:

![image](https://user-images.githubusercontent.com/6272557/102117875-e35d3c00-3e0c-11eb-80e7-be564494b077.png)

Errors in the container logs show:
DBUG::RESPONSE /socket.io/websocket  400
is happening very frequently

If I click on the "Welcome to Wave" message, it never loads. Restarting the server actually makes the message disappear.

**Comment by maccam912** [comment]
This repo is certainly pretty stale and unsupported. It sounds like maybe the client side javascript is referencing localhost when it ought to be using whatever hostname the page is being hosted on. Not sure if I have the time to fix this though, but feel free to fork this if you know where the issue is!
